session_name: default
windows:
  - name: default
    layout: tiled
    shell_command_before:
      - cd ~
      - clear
    panes:
      - echo "PANE 1"
      - echo "PANE 2"
      - echo "PANE 3"
      - echo "PANE 4"
