name: CI - Arch Linux
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
      SKIP_POST_SETUP: true
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Pacman
        run: |
            cd arch && ./init.sh
      - name: Simulate Setup
        run: |
            mkdir -p ~/.ssh
            pacman -Syyu --noconfirm --noprogressbar
            pacman -S --noconfirm --noprogressbar sudo
            cd arch && ./setup.sh
      - name: Post-Setup
        run: |
            ./post-setup.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
      - name: Simulate Stowing
        run: |
            sudo -u johnc bash -c 'mkdir -p $HOME/.dotfiles'
            sudo -u johnc bash -c 'mkdir -p $HOME/.local/state/dotstow'
            sudo -u johnc bash -c 'ln -s $HOME/.dotfiles $HOME/.local/state/dotstow/dotfiles'
            cp -r $PWD/* /home/johnc/.dotfiles/
            sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
            sudo -u johnc bash -c 'cd $HOME/.dotfiles/arch && ./stowme.sh'
