name: CI - Arch Linux
on:
  push:
    branches: ["master", "develop", "feature/*"]
  pull_request:
    branches: ["feature/*"]
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      SKIP_ADDING_USER: true
    steps:
      - uses: actions/checkout@v3
      # 'sudo' binary does not available on a docker image
      - name: Getting Started (First step)
        run: |
            pacman -Syyu --noconfirm --noprogressbar
            pacman -S --noconfirm --noprogressbar sudo
            cd arch && ./setup.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
