name: CI - Arch Linux
on:
  push:
    branches: ["master", "develop", "feature/*"]
  pull_request:
    branches: ["feature/*"]
  workflow_dispatch:
jobs:
  setup:
    runs-on: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Getting Started (First step)
        run: |
            cd arch && ./setup.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
