name: CI - Arch Linux
on:
  push:
    branches: ["master", "develop", "feature/*"]
  pull_request:
    branches: ["feature/*"]
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_POST_SETUP: true
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Pacman
        run: |
            cd arch && ./pacman.sh
      - name: Getting Started
        run: |
            mkdir -p ~/.ssh
            pacman -Syyu --noconfirm --noprogressbar
            pacman -S --noconfirm --noprogressbar sudo
            cd arch && ./setup.sh
      - name: Post-Setup
        run: |
            ./install-dotstow.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
