name: CI - Fedora
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    container: fedora:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
      SKIP_POST_SETUP: false
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        run: |
            echo "Initialize: Skipped. Fedora is working enough out-of-the-box..."
      - name: Add User
        run: |
            cd rhel && ./adduser.sh johnc
      - name: Getting Started
        run: |
            mkdir -p ~/.ssh
            cd rhel && ./setup.sh
      - name: Post-Setup
        run: |
            ./post-setup.sh
      - name: Installing Visual Studio Code
        run: |
            cd rhel && ./vscode.sh
      - name: Installing nodejs
        run: |
            ./nodejs.sh
      - name: Installing php
        run: |
            ./php.sh
      - name: Verify ccache
        run: |
            ccache -s
      - name: Install python3 with pyenv (installation test)
        run: |
            ./python.sh
      - name: Verify python3
        run: |
            sudo -u johnc bash -c 'python3 --version'
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
      - name: Simulate Stowing
        run: |
            sudo -u johnc bash -c 'mkdir -p $HOME/.dotfiles'
            sudo -u johnc bash -c 'mkdir -p $HOME/.local/state/dotstow'
            sudo -u johnc bash -c 'ln -s $HOME/.dotfiles $HOME/.local/state/dotstow/dotfiles'
            cp -r $PWD/* /home/johnc/.dotfiles/
            sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
            sudo -u johnc bash -c 'cd $HOME/.dotfiles/rhel && ./stowme.sh'
