name: CI - LEMP (Debian)
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    container: linuxconfig/lemp:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
      TEST_USER: johnc
      TEST_USER_HOME: /home/johnc
    steps:
      - uses: actions/checkout@v3
      - name: Add User
        run: |
          sh linux/systems/bin/dotfiles-adduser $TEST_USER
      - name: Setup some directories
        run: |
          mkdir -p $TEST_USER_HOME/.dotfiles
          mkdir -p $TEST_USER_HOME/.local/state/dotstow
          mkdir -p $TEST_USER_HOME/bin
          cp -r $PWD/* $TEST_USER_HOME/.dotfiles/
          chown -R $TEST_USER:$TEST_USER $TEST_USER_HOME
      - name: Getting Started
        run: |
          sudo -u $TEST_USER sh -c "cd $TEST_USER_HOME/.dotfiles && ./start.sh"
      - name: Installing dotstow
        run: |
          sudo -u $TEST_USER sh -c "cd $TEST_USER_HOME/.dotfiles && sh linux/systems/bin/dotfiles-dotstow"
      - name: Simulate Stowing
        run: |
          sudo -u $TEST_USER sh -c "cd $TEST_USER_HOME/.dotfiles && sh linux/systems/bin/dotfiles-cleanup"
          sudo -u $TEST_USER sh -c "cd $TEST_USER_HOME/.dotfiles && sh linux/systems/bin/dotfiles-ssh"
          sudo -u $TEST_USER sh -c "cd $TEST_USER_HOME/.dotfiles && sh arch/stowme.sh"
