name: CI - Ubuntu
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup some directories
        run: |
          mkdir -p $HOME/.dotfiles
          mkdir -p $HOME/.local/state/dotstow
          mkdir -p $HOME/bin
          cp -r $PWD/* $HOME/.dotfiles/
      - name: Getting Started
        run: |
          ./start.sh
      - name: Add User
        run: |
          sh linux/systems/bin/dotfiles-adduser
      - name: Simulate Stowing
        run: |
          sh linux/systems/bin/dotfiles-cleanup
          sh linux/systems/bin/dotfiles-ssh
          sh ubuntu/stowme.sh
