name: CI - Unit Test
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup some directories
        run: |
          mkdir -p $HOME/.dotfiles
          mkdir -p $HOME/.local/state/dotstow
          mkdir -p $HOME/.local/bin/org.jcchikikomori.dotfiles/bin
          mkdir -p $HOME/logs
          cp -r $PWD/* $HOME/.dotfiles/
      - name: Getting Started
        run: |
          ./start.sh
      - name: Execute post-setup (git)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-git
      - name: Execute post-setup (homebrew)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-homebrew install
      - name: Execute post-setup (python)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python install
      - name: Execute post-setup (pre-commit)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python--pre-commit
      - name: Execute post-setup (php)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-php install
      - name: Execute post-setup (ruby)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-ruby install
      - name: Simulate Stowing
        if: always()
        run: |
          sh ubuntu/stowme.sh
      - name: Generate list from $HOME dir
        if: always()
        run: |
          ls -lah $HOME >> $HOME/logs/userfilelslah.txt
          find $HOME -type d -name ".dotfiles" -prune -o -type d -name ".local" -prune -o -type d -name "bin" -prune -o -type d -name "logs" -prune -o -print > $HOME/logs/userfilelist.txt
      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotfiles-logs-ubuntu
          path: $HOME/logs
          retention-days: 30
          compression-level: 9
          include-hidden-files: true
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup some directories
        run: |
          mkdir -p $HOME/.dotfiles
          mkdir -p $HOME/.local/state/dotstow
          mkdir -p $HOME/.local/bin/org.jcchikikomori.dotfiles/bin
          mkdir -p $HOME/logs
          cp -r $PWD/* $HOME/.dotfiles/
      - name: Getting Started
        run: |
          ./start.sh
      - name: Execute post-setup (git)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-git
      - name: Execute post-setup (homebrew)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-homebrew install
      - name: Execute post-setup (python)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python install
      - name: Execute post-setup (pre-commit)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python--pre-commit
      - name: Execute post-setup (php)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-php install
      - name: Execute post-setup (ruby)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-ruby install
      - name: Simulate Stowing
        if: always()
        run: |
          sh arch/stowme.sh
      - name: Generate list from $HOME dir
        if: always()
        run: |
          ls -lah $HOME >> $HOME/logs/userfilelslah.txt
          find $HOME -type d -name ".dotfiles" -prune -o -type d -name ".local" -prune -o -type d -name "bin" -prune -o -type d -name "logs" -prune -o -print > $HOME/logs/userfilelist.txt
      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotfiles-logs-arch
          path: $HOME/logs
          retention-days: 30
          compression-level: 9
          include-hidden-files: true
  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup some directories
        run: |
          mkdir -p $HOME/.dotfiles
          mkdir -p $HOME/.local/state/dotstow
          mkdir -p $HOME/.local/bin/org.jcchikikomori.dotfiles/bin
          mkdir -p $HOME/logs
          cp -r $PWD/* $HOME/.dotfiles/
      - name: Getting Started
        run: |
          ./start.sh
      - name: Execute post-setup (git)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-git
      - name: Execute post-setup (homebrew)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-homebrew install
      - name: Execute post-setup (python)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python install
      - name: Execute post-setup (pre-commit)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-python--pre-commit
      - name: Execute post-setup (php)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-php install
      - name: Execute post-setup (ruby)
        run: |
          ./linux/systems/.local/bin/org.jcchikikomori.dotfiles/bin/dotfiles-ruby install
      - name: Simulate Stowing
        if: always()
        run: |
          sh rhel/stowme.sh
      - name: Generate list from $HOME dir
        if: always()
        run: |
          ls -lah $HOME >> $HOME/logs/userfilelslah.txt
          find $HOME -type d -name ".dotfiles" -prune -o -type d -name ".local" -prune -o -type d -name "bin" -prune -o -type d -name "logs" -prune -o -print > $HOME/logs/userfilelist.txt
      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotfiles-logs-fedora
          path: $HOME/logs
          retention-days: 30
          compression-level: 9
          include-hidden-files: true
