name: CI - Ubuntu
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Initialize with Essentials
        run: |
          cd debian && ./init.sh
      - name: Getting Started
        run: |
          ./start.sh
      - name: Add User
        run: |
          sh linux/systems/bin/dotfiles-adduser johnc
      - name: Installing dotstow
        run: |
          sh linux/systems/bin/dotfiles-dotstow
      - name: Simulate Stowing
        run: |
          mkdir -p /home/johnc/.dotfiles
          mkdir -p /home/johnc/.local/state/dotstow
          ls -lah $PWD
          cp -r $PWD/* /home/johnc/.dotfiles/
          sudo -u johnc bash -c 'mkdir -p $HOME/bin'
          sudo -u johnc bash -c 'cp $HOME/.dotfiles/linux/systems/bin/dotfiles-cleanup $HOME/bin/'
          sudo -u johnc bash -c 'cp $HOME/.dotfiles/linux/systems/bin/dotfiles-ssh $HOME/bin/'
          sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
          sudo -u johnc bash -c 'cd $HOME/.dotfiles/debian && ./stowme.sh'
