name: CI - Ubuntu
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
      SKIP_POST_SETUP: true
    steps:
      - uses: actions/checkout@v3
      - name: Initialize with Essentials
        run: |
            cd debian && sudo bash init.sh
      - name: Getting Started
        run: |
            cd debian && ./setup.sh
      - name: Add User
        run: |
            cd debian && ./adduser.sh
      - name: Verify ccache
        run: |
            ccache -s
      - name: Install python3 with pyenv
        run: |
            ./python.sh
            which pyenv
      - name: Verify python3
        run: |
            sudo -u johnc bash -c 'pyenv global 3.11.4 && pyenv rehash && python3 --version'
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
      - name: Simulate Stowing
        run: |
            sudo -u johnc bash -c 'mkdir -p $HOME/.dotfiles'
            sudo -u johnc bash -c 'mkdir -p $HOME/.local/state/dotstow'
            sudo -u johnc bash -c 'ln -s $HOME/.dotfiles $HOME/.local/state/dotstow/dotfiles'
            cp -r $PWD/* /home/johnc/.dotfiles/
            sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
            sudo -u johnc bash -c 'cd $HOME/.dotfiles/debian && ./stowme.sh'
