name: CI - Ubuntu
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
    steps:
      - uses: actions/checkout@v3
      - name: Initialize with Essentials
        run: |
            cd debian && sudo bash init.sh
      - name: Simulate Setup
        run: |
            cd debian && ./setup.sh
      - name: Post-Setup
        run: |
            ./post-setup.sh
      - name: Add User
        run: |
            cd debian && ./adduser.sh
      - name: Verify ccache
        run: |
            ccache -s
      - name: Install python3 with pyenv (installation test)
        run: |
            ./python.sh
      - name: Install ruby with rbenv (installation test)
        run: |
            ./ruby.sh
      - name: Verify python3
        run: |
            sudo -u johnc bash -c 'python3 --version'
      - name: Verify ruby
        run: |
            sudo -u johnc bash -c 'rbenv versions'
            sudo -u johnc bash -c 'ruby -v'
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
      - name: Simulate Stowing
        run: |
            sudo -u johnc bash -c 'mkdir -p $HOME/.dotfiles'
            sudo -u johnc bash -c 'mkdir -p $HOME/.local/state/dotstow'
            sudo -u johnc bash -c 'ln -s $HOME/.dotfiles $HOME/.local/state/dotstow/dotfiles'
            cp -r $PWD/* /home/johnc/.dotfiles/
            sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
            sudo -u johnc bash -c 'cd $HOME/.dotfiles/debian && ./stowme.sh'
