name: CI - Ubuntu
on:
  push:
    branches: ["master", "develop", "feature/*"]
  pull_request:
    branches: ["feature/*"]
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_POST_SETUP: true
    steps:
      - uses: actions/checkout@v3
      - name: Initialize with Essentials
        run: |
            cd debian && sudo bash init.sh
      - name: Getting Started
        run: |
            cd debian && ./setup.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
