name: CI - Ubuntu
on:
  pull_request:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      SKIP_SETTING_USER: true
      SKIP_INSTALL_PROGLANG: false
      SKIP_POST_SETUP: true
    steps:
      - uses: actions/checkout@v3
      - name: Initialize with Essentials
        run: |
            cd debian && sudo bash init.sh
      - name: Getting Started
        run: |
            cd debian && ./setup.sh
      - name: Add User
        run: |
            cd debian && ./adduser.sh
      - name: Installing dotstow
        run: |
            ./install-dotstow.sh
      - name: Simulate Stowing
        run: |
            sudo mkdir -p /home/johnc/.dotfiles
            sudo mkdir -p /home/johnc/.local/state/dotstow
            ls -lah $PWD
            sudo cp -r $PWD/* /home/johnc/.dotfiles/
            sudo -u johnc bash -c 'ls -lah $HOME/.dotfiles/'
            sudo -u johnc bash -c 'cd $HOME/.dotfiles/debian && ./stowme.sh'
